theme = "everforest_dark"

[editor]
line-number = "relative"
mouse = true
middle-click-paste = true
scroll-lines = 1
bufferline = "multiple"
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-absolute-path", "file-modification-indicator", "read-only-indicator"]
right = ["diagnostics", "selections", "position-percentage", "file-encoding", "file-line-ending", "file-type", "total-line-numbers"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.indent-guides]
render = true
character = "╎"

[keys.normal]
# Move line up/down using A-k, A-j
"A-k" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before"
]
"A-j" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_down",
  "paste_before"
]

[keys.select]
# Move line up/down using A-k, A-j
"A-k" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before"
]
"A-j" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_down",
  "paste_before"
]

# Config Mode
[keys.normal."C-backspace"]
r = ":config-reload"
o = ":config-open"
l = ":o ~/.config/helix/languages.toml"
