[[language]]
name = "yaml"
language-servers = ["ansible-language-server", "yaml-language-server"]
file-types = ["yml", "yaml"]

[[language]]
name = "markdown"
language-servers = ["marksman", "mdpls"]

[language-server.mdpls]
command = "/Users/asj/.cargo/bin/mdpls"
config = { markdown.preview.auto = true, markdown.preview.browser = "firefox" }
